version: "3"
services:
  pprojectoil:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: oildb
    ports:
      - "5010:5010"
    restart: always
    depends_on:
      - postgres

  postgres:
    image: postgres:16.0-alpine
    container_name: oil_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: oildb
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always

volumes:
  postgres: